# -*- coding: utf-8 -*-
"""hello-world(streamlit).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-4U3fOKHAcuciD2dX5RIYuLSwxQtD_3
"""

import streamlit as st

st.write(
    """
    # My first app
    Hello, para calon praktisi data masa depan!
    """
)